display_name: Lift Measurement Config
name: lift_measurement_config
description: '<p>A Lift Measurement Configuration (LMC), which is a lift study. This
  groups

  all associated Brand Lift, Conversion Lift, and Search Lift measurements.</p>'
attributed_views:
- customer
attributes:
- lift_measurement_config.campaigns
- lift_measurement_config.conversion_actions
- lift_measurement_config.conversion_lift_holdback_ratio_micros
- lift_measurement_config.lift_measurement_config_id
- lift_measurement_config.name
- lift_measurement_config.resource_name
- lift_measurement_config.single_measurement_question_set.advertiser_preferred_choice
- lift_measurement_config.single_measurement_question_set.competitor_choices
- lift_measurement_config.single_measurement_question_set.question_measurements
- lift_measurement_config.single_measurement_question_set.question_text_intended_action
- lift_measurement_config.single_measurement_question_set.question_text_subject_type
- lift_measurement_config.survey_language
- customer.auto_tagging_enabled
- customer.call_reporting_setting.call_conversion_action
- customer.call_reporting_setting.call_conversion_reporting_enabled
- customer.call_reporting_setting.call_reporting_enabled
- customer.contains_eu_political_advertising
- customer.conversion_tracking_setting.accepted_customer_data_terms
- customer.conversion_tracking_setting.conversion_tracking_id
- customer.conversion_tracking_setting.conversion_tracking_status
- customer.conversion_tracking_setting.cross_account_conversion_tracking_id
- customer.conversion_tracking_setting.enhanced_conversions_for_leads_enabled
- customer.conversion_tracking_setting.google_ads_conversion_customer
- customer.currency_code
- customer.customer_agreement_setting.accepted_lead_form_terms
- customer.descriptive_name
- customer.final_url_suffix
- customer.has_partners_badge
- customer.id
- customer.image_asset_auto_migration_done
- customer.image_asset_auto_migration_done_date_time
- customer.local_services_settings.granular_insurance_statuses
- customer.local_services_settings.granular_license_statuses
- customer.location_asset_auto_migration_done
- customer.location_asset_auto_migration_done_date_time
- customer.manager
- customer.optimization_score
- customer.optimization_score_weight
- customer.pay_per_conversion_eligibility_failure_reasons
- customer.remarketing_setting.google_global_site_tag
- customer.resource_name
- customer.status
- customer.test_account
- customer.time_zone
- customer.tracking_url_template
- customer.video_brand_safety_suitability
- customer.video_customer.third_party_integration_partners.brand_lift_integration_partners
- customer.video_customer.third_party_integration_partners.brand_safety_integration_partners
- customer.video_customer.third_party_integration_partners.conversion_attribution_integration_partners
- customer.video_customer.third_party_integration_partners.reach_integration_partners
- customer.video_customer.third_party_integration_partners.viewability_integration_partners
segments:
- segments.age_range
- segments.brand_lift_measurement_type
- segments.conversion_action
- segments.conversion_action_name
- segments.conversion_lift_conversion_category
- segments.conversion_lift_end_date
- segments.conversion_lift_included_conversion_action_types
- segments.conversion_lift_start_date
- segments.country
- segments.country_localized_name
- segments.date
- segments.device
- segments.experiment_arm
- segments.gender
metrics:
- metrics.absolute_brand_lift
- metrics.absolute_brand_lift_p90_lower_bound
- metrics.absolute_brand_lift_p90_upper_bound
- metrics.absolute_brand_lift_p_value
- metrics.brand_lift_baseline_positive_response_rate
- metrics.brand_lift_baseline_positive_response_rate_p90_lower_bound
- metrics.brand_lift_baseline_positive_response_rate_p90_upper_bound
- metrics.brand_lift_exposed_positive_responder_fractional_cookies
- metrics.brand_lift_exposed_positive_responder_fractional_cookies_p90_lower_bound
- metrics.brand_lift_exposed_positive_responder_fractional_cookies_p90_upper_bound
- metrics.brand_lift_exposed_positive_response_rate
- metrics.brand_lift_exposed_positive_response_rate_p90_lower_bound
- metrics.brand_lift_exposed_positive_response_rate_p90_upper_bound
- metrics.brand_lift_responses_exposed
- metrics.brand_lift_responses_suppressed
- metrics.brand_lift_suppressed_positive_responder_fractional_cookies
- metrics.brand_lift_suppressed_positive_responder_fractional_cookies_p90_lower_bound
- metrics.brand_lift_suppressed_positive_responder_fractional_cookies_p90_upper_bound
- metrics.brand_lift_total_responses
- metrics.conversion_lift_baseline_conversion_value
- metrics.conversion_lift_baseline_conversions
- metrics.conversion_lift_exposed_conversion_value
- metrics.conversion_lift_exposed_conversions
- metrics.cost_per_incremental_conversion
- metrics.cost_per_incremental_conversion_p90_lower_bound
- metrics.cost_per_incremental_conversion_p90_upper_bound
- metrics.cost_per_incremental_conversion_winner_score
- metrics.cost_per_lifted_cookie
- metrics.cost_per_lifted_cookie_p90_lower_bound
- metrics.cost_per_lifted_cookie_p90_upper_bound
- metrics.fractional_lifted_cookies
- metrics.fractional_lifted_cookies_p90_lower_bound
- metrics.fractional_lifted_cookies_p90_upper_bound
- metrics.headroom_brand_lift
- metrics.headroom_brand_lift_p90_lower_bound
- metrics.headroom_brand_lift_p90_upper_bound
- metrics.incremental_conversion_value
- metrics.incremental_conversion_value_p90_lower_bound
- metrics.incremental_conversion_value_p90_upper_bound
- metrics.incremental_conversion_value_p_value
- metrics.incremental_conversion_value_per_cost
- metrics.incremental_conversion_value_per_cost_p90_lower_bound
- metrics.incremental_conversion_value_per_cost_p90_upper_bound
- metrics.incremental_conversion_value_per_cost_winner_score
- metrics.incremental_conversion_value_winner_score
- metrics.incremental_conversions
- metrics.incremental_conversions_p90_lower_bound
- metrics.incremental_conversions_p90_upper_bound
- metrics.incremental_conversions_p_value
- metrics.incremental_conversions_winner_score
- metrics.relative_brand_lift
- metrics.relative_brand_lift_p90_lower_bound
- metrics.relative_brand_lift_p90_upper_bound
- metrics.relative_conversion_lift
- metrics.relative_conversion_lift_p90_lower_bound
- metrics.relative_conversion_lift_p90_upper_bound
- metrics.relative_conversion_value_lift
- metrics.relative_conversion_value_lift_p90_lower_bound
- metrics.relative_conversion_value_lift_p90_upper_bound
