display_name: Product Category Constant
name: product_category_constant
description: <p>A Product Category.</p>
attributed_views: []
attributes:
- product_category_constant.category_id
- product_category_constant.level
- product_category_constant.localizations
- product_category_constant.product_category_constant_parent
- product_category_constant.resource_name
- product_category_constant.state
segments: []
metrics: []
